CREATE SCHEMA `appid` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
 
CREATE TABLE `appid`.`data` (
  `PID` VARCHAR(255) NOT NULL COMMENT 'ID to identify user',
  `APPID` VARCHAR(50) NOT NULL COMMENT 'Generated APP-ID',
  `COUNTRY` VARCHAR(5) NOT NULL COMMENT 'IOC of citizen country',
  `SECURITYQUESTION` VARCHAR(255) NOT NULL COMMENT 'chosen question utf8',
  `SECURITYANSWER` VARCHAR(255) NOT NULL COMMENT 'chosen answer utf8 (original)',
  `CREATIONDATE` DATETIME NOT NULL,
  PRIMARY KEY (`PID`)
) ENGINE=InnoDB;

CREATE TABLE `appid`.`previous` (
  `NEWPID` VARCHAR(255) NOT NULL,
  `OLDPID` VARCHAR(255) NOT NULL,
  `CHANGEDATE` DATETIME NOT NULL
) ENGINE=InnoDB;
  
CREATE TABLE `appid`.`log` (
  `LOGID` INT NOT NULL auto_increment,
  `LOGTYPE` INT NOT NULL,
  `LOGDATE` DATETIME NOT NULL,
  `LOGCOMMENT` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`LOGID`)
) ENGINE=InnoDB;

CREATE TABLE `appid`.`fail` (
    `PID` VARCHAR(255) NOT NULL COMMENT 'ID to identify user with failed login',
    `LOGINDATE` DATETIME NOT NULL
) ENGINE=MEMORY;

CREATE EVENT `appid`.`clear_fail` 
ON SCHEDULE EVERY 1 MINUTE
DO DELETE FROM `appid`.`fail` WHERE LOGINDATE < (NOW() - INTERVAL 10 MINUTE);